### ISSUE TITLE
Potential bug when RECHECK is False

### ISSUE THREAD

**Issue by bretwalker** [oliwarner/django-multifactor#21]
I think there may be a bug when `RECHECK` is `False`.
It's not behaving the way I expect, though I may misunderstand something.

```
def write_session(request, key):
    """Write the multifactor session with the verified key"""
    request.session["multifactor"] = [
        (
            key.key_type if key else None,
            key.id if key else None,
            timezone.now().timestamp(),
            next_check() if mf_settings["RECHECK"] else False
        ),
        *filter(
            lambda tup: not key or tup[1] != key.id,
            request.session.get('multifactor', [])
        ),
    ]
```

```
def active_factors(request):
    # automatically expire old factors
    now = timezone.now().timestamp()
    factors = request.session["multifactor"] = [
        *filter(
            lambda tup: tup[3] > now,
            request.session.get('multifactor', [])
        ),
    ]
    return factors
```

Given the above code, I believe `active_factors` will always return an empty list and reset `request.session["multifactor"] ` if `mf_settings["RECHECK"]` is `False`, which will end up asking the user to re-authenticate over and over.

I would expect the token expiration (`tup[3]`) to be `datetime.datetime.max` when `mf_settings["RECHECK"]` is `False`.

**Comment by oliwarner** [comment]
Rather than preserve an arbitrarily long datetime, I've made the bit that does expiry checking look for False, and allow it through.

Thanks for your help again.
