### ISSUE TITLE
FIDO2 page immediately errors in Safari

### ISSUE THREAD

**Issue by bretwalker** [oliwarner/django-multifactor#22]
It seems like FIDO2 operations on Apple devices require explicit user interaction in order to operate.

With the current automatic call to `authenticate` on the FIDO2 `add` page, I immediately see a red page with the error "NotAllowedError: This request has been cancelled by the user." on the page and "User gesture is not detected. To use the WebAuthn API, call 'navigator.credentials.create' within user activated events." in the console.

There is more information on the error here: https://support.yubico.com/hc/en-us/articles/360022004600-No-reaction-when-using-WebAuthn-on-macOS-iOS-and-iPadOS

**Comment by oliwarner** [comment]
I've tried something that should show a button if the script fails. I don't have a device to test it on, could you let me know if it works? I haven't published the package yet, so install via:

    pip install git+git://github.com/oliwarner/django-multifactor.git#egg=django-multifactor

Or by tar and pip if you prefer: [django-multifactor-0.4.5.tar.gz](https://github.com/oliwarner/django-multifactor/files/6693331/django-multifactor-0.4.5.tar.gz)

**Comment by oliwarner** [comment]
This is released. Still unable to personally verify but reopen if it's a problem.
