### ISSUE TITLE
Release Django 3.2 supported version

### ISSUE THREAD

**Issue by StevenMapes** [oliwarner/django-multifactor#24]
Currently the latest version on Pypi is 0.4.3 which is setup to only support Django 3.1.*, how far are you from releasing 0.4.4 - 0.4.6?

**Comment by jatindergit** [comment]
@oliwarner I am also waiting for the same

**Comment by StevenMapes** [comment]
> @oliwarner I am also waiting for the same

Take a look at my fork  -https://github.com/StevenMapes/django-multifactor I've made changes which I've pushed back here as three PRs. One is for this, another is for #28 and then a new feature created as #27 . My hope is that they are merged back into this by Oli

**Comment by jatindergit** [comment]
@StevenMapes and @oliwarner looks like https://github.com/oliwarner/django-multifactor/pull/27 not merged. Please confirm once. As I have just installed django-multifactor==0.4.3 and it did the following
Attempting uninstall: django
    Found existing installation: Django 3.2
    Uninstalling Django-3.2:
      Successfully uninstalled Django-3.2
    Running setup.py install for python-u2flib-server ... done
    Running setup.py install for fido2 ... done
Successfully installed django-3.1.13 django-multifactor-0.4.3 ecdsa-0.17.0 fido2-0.8.1 pyotp-2.6.0 python-jose-3.3.0 python-u2flib-server-5.0.1

It just uninstalled the django 3.2 and install django 3.1

**Comment by StevenMapes** [comment]
@jatindergit - none of my PRs have been merged in, I'm not a maintainer here just a user who likes the project, uses it and wants to help out.

If you want to install the latest version from here you have to install it from GIT not from pypi. So use ```pip install git+https://github.com/oliwarner/django-multifactor```. That's what I've done as I'm using Django 3.2 and have been start to test it with Django 4.

If you want to use my latest fork with all my PRs then install that from the 0.4.7 tag I created on my fork ```pip install git+https://github.com/StevenMapes/django-multifactor@0.4.7```. It has the Django Admin fix which may cause you issues without it as it did me.

I'm going to maintain my fork whilst the PRs aren't merged or rejected by Oli. Once he decides if he wants to include them or not I'll then remove my fork and just use it for PRs or keep it if I need and rejected functionality

**Comment by oliwarner** [comment]
Apologies for my absence on your PRs @StevenMapes. Kids are back at school now so I should have a couple of hours to chow through them today, do some testing and release.

**Comment by StevenMapes** [comment]
Not a problem sir, it's a handy project you created and I know how it can be OS projects can be a time burner especially when RL gets busy so all in your own time

**Comment by oliwarner** [comment]
Released!

I've only given it the very lightest of shakes but hopefully the changes are light enough that I've not introduced any new bugs. @StevenMapes  Thank you for your patches. I'll try adding some of my own before the year's out :)
