### ISSUE TITLE
Roadmap for future functionality

### ISSUE THREAD

**Issue by mariadb-BryanAlsdorf** [oliwarner/django-multifactor#4]
As I implement this for my project I'm coming up with a list of things I still need to implement. Some of these make sense to implement upstream but before I prepare PR's I wanted to check if you had any plans for these items or objections to including them in the project.

- backup code fallback functionality (my preference would be for a single backup code that when used disables 2FA instead of multiple single use codes)
- Signals for MFA events (key registered, key disabled, authentication, etc)

**Comment by StevenMapes** [comment]
+1 from me. Did you get anywhere with PRs for this as I'd be interested in both, especially the one-time use backup codes, myself

**Comment by mariadb-BryanAlsdorf** [comment]
@StevenMapes I reached a point where I had diverged so much I scrapped the idea of submitting PR's and wrote code specific to my needs so unfortunately I'm not going to be any help.
