### ISSUE TITLE
Upgrade to support Fido2 1.1.0

### ISSUE THREAD

**Issue by StevenMapes** [oliwarner/django-multifactor#44]
version 1.0.0. of Fido2 is stable and adds in some updates- https://github.com/Yubico/python-fido2/blob/main/NEWS
version 1.1.0. of Fido2 is stable as well

Both drop support for Python 3.6 though but that went EOL at the end of last year -https://endoflife.date/python

Changes will be required before upgrading the dependency so I would suggest doing this after merging in the PRs for support for Django 4.2 and Python up to 3.11

**Comment by StevenMapes** [comment]
Updating the issue since 1.1.0 has been released but also to note that changes will be required in order to support the latest version

**Comment by StevenMapes** [comment]
I've looked into this and there are some changes that are required so I will take a crack at that sometime this month but ideally I'd like my other PR to be reviews and wither accepted or rejected first so I can start with a cleaner fork as I'll be making the change on top of the updates to support Python 3.10, 3.11 and Django up to 4.2

**Comment by oliwarner** [comment]
I almost gave up here but I think it's working. Almost broke my keyboard in a fit of *why is nothing encoding properly*, before noticing they've changed how all this stuff works so it works better with json, but only if you turn on a magic flag.

The downside of this is poetry pegs package requirements together, so we're inadvertently dropping a few lower versions of Python to match fido2. Minimum is now 3.7.

I think what we have now is cleaner. I'll test this on my own projects and I'll gear this and some CSS cleanup at a 0.6 release.

**Comment by StevenMapes** [comment]
I wouldn't worry about Python 3.7 support as that is no longer supported by either Python (https://endoflife.date/python) or Django, both are 3.8 minimum now :)

Your efforts are appreciated

**Comment by oliwarner** [comment]
Thanks. I've released 0.6.0rc0 to PyPI.

Only giving it a "works for me" badge so far, but it's been smooth sailing so far.

**Comment by StevenMapes** [comment]
I have tested this with one of my main projects and so far everything is working okay. I can produce and scan a new QR fido record and then use it to authenticate
