### ISSUE TITLE
django-multifactor pulls incommmpatible dependency on install

### ISSUE THREAD

**Issue by ADimeo** [oliwarner/django-multifactor#6]
When installing django-multifactor via `pip install django-multifactor` the `fido2` dependency is installed with version 0.8.1, which is backward incompatible. 
This results in an importError when starting the server (ImportError: cannot import name 'RelyingParty' from 'fido2.server' (/home/antonio/Documents/uni/vl_material/bp/mfa/.venv/lib/python3.7/site-packages/fido2/server.py))

Manually downgrading the dependency to version 0.7.0 resolves the issue.

**Comment by oliwarner** [comment]
I have updated our side (and requirements) to be compatible with the latest version of fido2.
