### ISSUE TITLE
FACTORS setting doesn't seem to be respected

### ISSUE THREAD

**Issue by godswearhats** [oliwarner/django-multifactor#64]
I've configured my set up to only have TOTP as a factor using

MULTIFACTOR = {
    # other settings ...
    'FACTORS': ['TOTP'],
}

However, when users visit the url at `multifactor:add`, they are given the option of both FIDO2 and TOTP. This may well be a misunderstanding on my part on how things are meant to be configured, but I cannot figure that out from the documentation. Any help appreciated.

**Comment by oliwarner** [comment]
Should be in PyPI shortly. Thanks again.
