### ISSUE TITLE
Typos in some messages/files (TOTP vs TOPT)?

### ISSUE THREAD

**Issue by sebastiaopf** [oliwarner/django-multifactor#86]
I think I've come across a few typos in messages where "TOTP" is written as "TOPT". I've found them at:

- factors/totp.py:42
- multifactor/add.html:28
- help.html:20
- multifactor/models.py:13 (variable name)

Are these intentional by any chance and I am missing something or they are real typos?

![image](https://github.com/oliwarner/django-multifactor/assets/2914850/960ac53e-62c4-4b80-a9f0-267086c51d89)

**Comment by StevenMapes** [comment]
I'd say that they are typos.

**Comment by oliwarner** [comment]
Good catch. Thank you.

**Comment by sebastiaopf** [comment]
Thanks to both of you for the fast response. This is a great package.
