### ISSUE TITLE
TOTP: Form input type change - UX

### ISSUE THREAD

**Issue by StevenMapes** [oliwarner/django-multifactor#88]
As TOTPs are always numeric I suggest that we change the input field within the TOTP/add.html template from type="text" to type="number", this will give a better user experience on mobile devices as it will change the keyboard to numbers only.

**Comment by oliwarner** [comment]
I avoided `type="number"` on purpose. Some browsers append silly +/- spinners on to them, and some had problems with leading zeros. There's [a good historical discussion about this on SO](https://stackoverflow.com/questions/8437529/html5-input-type-number-removes-leading-zero). But there does seem to be a nice compromise:

    <input type="text" inputmode="numeric" pattern="[0-9]{6}">

I'll have a go, see if it works.

**Comment by oliwarner** [comment]
Yup, that works. I've done the same for the fallback (eg email) input too which just uses a variable-length version.
